app = 'divy-pastebin'
primary_region = 'hkg'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[experimental]
  auto_rollback = true

[[mounts]]
  source = 'storage'
  destination = '/var/storage'

[http_service]
  internal_port = 6162
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
